name: check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Ensure `wit-deps` runs properly with a given version with a given version
  wit-deps-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - github.com/vados-cosmonic/wit-wasmcloud-postgres
        tag:
          - main
    steps:
    - uses: actions/checkout@v2
    - uses: taiki-e/cache-cargo-install-action@v2
      with:
        tool: wit-deps-cli
    - name: Create deps.toml file
      shell: bash
      run: |
        echo 'postgres = "https://${{ matrix.repo }}/archive/${{ matrix.tag }}.tar.gz"' > wit/deps.toml;
    - run: wit-deps
